package com.ngxson;

class Q2Fibonaci {
	/*
	 * https://projecteuler.net/problem=2
	 * answer=4613732
	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
	 By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
	find the sum of the even-valued terms.
	 */
	public static void main(String[] arg) {
		
		int max = 4000000;
		
		int fibo1 = 1;
		int fibo2 = 1;
		int count = 1;
		int sum = 0;
		int result = 0;
		while(fibo2 < max) {
			count = count +1;
			int temp = fibo1 + fibo2;
			fibo1 = fibo2;
			fibo2 = temp;
			sum = sum + fibo2;
			if((fibo2 % 2) == 0) result = result + fibo2; //result
		}
		System.out.println("answer="+result);
	}
}